 // @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  basicsSidebar: [
    {type: 'autogenerated', dirName: 'basics'}
  ],
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'tutorial/intro',
      label: '入门教程',
    },
    {
      type: 'category',
      label: '跑通第一个量化程序',
      link: {
        type: 'doc',
        id: 'tutorial/run-first-quant-program/intro',
      },
      collapsed: false,
      items: [
        {type: 'doc', id: 'tutorial/run-first-quant-program/basic-setup'},
        {type: 'doc', id: 'tutorial/run-first-quant-program/strategy-writing'},
        {type: 'doc', id: 'tutorial/run-first-quant-program/backtesting'},
        {type: 'doc', id: 'tutorial/run-first-quant-program/live-deployment'},
      ]
    },
    {
      type: 'category',
      label: '云服务器部署freqtrade',
      link: {
        type: 'doc',
        id: 'tutorial/cloud-deploy-freqtrade/intro',
      },
      collapsed: false,
      items: [
        {type: 'doc', id: 'tutorial/cloud-deploy-freqtrade/why-cloud'},
        {type: 'doc', id: 'tutorial/cloud-deploy-freqtrade/dev-tools'},
        {type: 'doc', id: 'tutorial/cloud-deploy-freqtrade/aws-free-ec2'},
        {type: 'doc', id: 'tutorial/cloud-deploy-freqtrade/bot-deploy'},
        {type: 'doc', id: 'tutorial/cloud-deploy-freqtrade/vultr'},
      ]
    },
    {
      type: 'category',
      label: 'Freqtrade相关',
      link: {
        type: 'doc',
        id: 'tutorial/freqtrade-related/intro',
      },
      collapsed: false,
      items: [
        {type: 'doc', id: 'tutorial/freqtrade-related/sqlite-database-structure'},
        {type: 'doc', id: 'tutorial/freqtrade-related/delete-sqlite-anomalies'},
      ]
    },
    {
      type: 'category',
      label: 'n8n+链上数据监控',
      link: {
        type: 'doc',
        id: 'tutorial/n8n-onchain-monitoring/intro',
      },
      collapsed: false,
      items: []
    },
    {
      type: 'category',
      label: 'n8n+链上监控+X监测=》跟单信号',
      link: {
        type: 'doc',
        id: 'tutorial/n8n-onchain-x-signal/intro',
      },
      collapsed: false,
      items: [
        {type: 'doc', id: 'tutorial/n8n-onchain-x-signal/monitor-onchain-data'},
      ]
    }
  ],
  strategySidebar: [
    {type: 'autogenerated', dirName: 'strategy'}
  ],
  aiSidebar: [
    {
      type: 'doc',
      id: 'ai/intro',
      label: 'AI相关',
    },
    {
      type: 'category',
      label: 'n8n',
      link: {
        type: 'doc',
        id: 'ai/n8n/intro',
      },
      collapsed: false,
      items: [
        {type: 'doc', id: 'ai/n8n/n8n-free-deployment'},
        {type: 'doc', id: 'ai/n8n/n8n-send-telegram-message'},
      ]
    },
    {
      type: 'category',
      label: '儿童绘本视频',
      link: {
        type: 'doc',
        id: 'ai/picture-book-video/intro',
      },
      collapsed: false,
      items: [
        {type: 'doc', id: 'ai/picture-book-video/01-environment-setup'},
        {type: 'doc', id: 'ai/picture-book-video/02-story-generation'},
        {type: 'doc', id: 'ai/picture-book-video/03-storyboard-generation'},
        {type: 'doc', id: 'ai/picture-book-video/04-video-generation'},
        {type: 'doc', id: 'ai/picture-book-video/05-voice-generation'},
        {type: 'doc', id: 'ai/picture-book-video/06-n8n-automation'},
        {type: 'doc', id: 'ai/picture-book-video/07-video-composition'},
        {type: 'doc', id: 'ai/picture-book-video/08-optimization-publishing'},
      ]
    }
  ],
  toolsSidebar: [
    {type: 'autogenerated', dirName: 'tools'}
  ],
  booksSidebar: [
    {type: 'autogenerated', dirName: 'books'}
  ],
  liveTradingSidebar: [
    {type: 'autogenerated', dirName: 'live-trading'}
  ],
  aboutSidebar: [
    {type: 'autogenerated', dirName: 'about'}
  ],
};

module.exports = sidebars;